//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario_des
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guia()
        {
            this.Equipo = new HashSet<Equipo>();
        }
    
        public int GuiaId { get; set; }
        public Nullable<int> NumeroGuia { get; set; }
        public Nullable<int> ProveedorId { get; set; }
        public string OrdenCompra { get; set; }
        public string NotaVenta { get; set; }
        public Nullable<System.DateTime> FechaGuia { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> CreadorId { get; set; }
        public Nullable<int> NumeroFactura { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipo> Equipo { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
