//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario_des
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventarioSoporteSistemas_desEntities : DbContext
    {
        public InventarioSoporteSistemas_desEntities()
            : base("name=InventarioSoporteSistemas_desEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CentroCosto> CentroCosto { get; set; }
        public virtual DbSet<Colaborador> Colaborador { get; set; }
        public virtual DbSet<Comuna> Comuna { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Distribucion> Distribucion { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<EstadoEquipo> EstadoEquipo { get; set; }
        public virtual DbSet<Guia> Guia { get; set; }
        public virtual DbSet<MacroEmpresa> MacroEmpresa { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<ProyectoConexion> ProyectoConexion { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<SistemaOperativo> SistemaOperativo { get; set; }
        public virtual DbSet<SubEstadoEquipo> SubEstadoEquipo { get; set; }
        public virtual DbSet<TipoEquipo> TipoEquipo { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<SP_DB_Obtener_MyTE_Result> SP_DB_Obtener_MyTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DB_Obtener_MyTE_Result>("SP_DB_Obtener_MyTE");
        }
    
        public virtual ObjectResult<SP_DB_Obtener_Cuentas_Result> SP_DB_Obtener_Cuentas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DB_Obtener_Cuentas_Result>("SP_DB_Obtener_Cuentas");
        }
    }
}
