//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario_des
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoConexion
    {
        public int CoId { get; set; }
        public int ProyectoId { get; set; }
        public int MacroEmpresaId { get; set; }
        public int EmpresaId { get; set; }
        public int CCId { get; set; }
        public int UbicacionId { get; set; }
        public int ComunaId { get; set; }
        public int DireccionId { get; set; }
    
        public virtual CentroCosto CentroCosto { get; set; }
        public virtual Comuna Comuna { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual MacroEmpresa MacroEmpresa { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
